sudo: required
services:
  - docker

before_install:
  - docker build -t jongaspar/docker-react -f Dockerfile.dev .

script:
  - docker run jongaspar/docker-react npm run test -- --coverage

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker"
#   env: "Docker-env"
#   bucket_name: __________
#   bucket_path: __________
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"